
"""First migration

Revision ID: e1dff16d9bd1
Revises: 0018_user_slash_commands
Create Date: 2026-05-15 17:02:10.886216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1dff16d9bd1'
down_revision: Union[str, None] = '0018_user_slash_commands'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhooks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('events', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('webhooks_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('webhooks_pkey'))
    )
    op.create_index(op.f('webhooks_user_id_idx'), 'webhooks', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('webhook_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], name=op.f('webhook_deliveries_webhook_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('webhook_deliveries_pkey'))
    )
    op.create_index(op.f('webhook_deliveries_created_at_idx'), 'webhook_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('webhook_deliveries_webhook_id_idx'), 'webhook_deliveries', ['webhook_id'], unique=False)
    op.drop_index(op.f('ix_channel_bots_platform'), table_name='channel_bots')
    op.create_index(op.f('channel_bots_platform_idx'), 'channel_bots', ['platform'], unique=False)
    op.drop_index(op.f('ix_channel_identities_platform'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_platform_user_id'), table_name='channel_identities')
    op.drop_index(op.f('ix_channel_identities_user_id'), table_name='channel_identities')
    op.create_index(op.f('channel_identities_platform_idx'), 'channel_identities', ['platform'], unique=False)
    op.create_index(op.f('channel_identities_platform_user_id_idx'), 'channel_identities', ['platform_user_id'], unique=False)
    op.create_index(op.f('channel_identities_user_id_idx'), 'channel_identities', ['user_id'], unique=False)
    op.drop_index(op.f('ix_channel_sessions_bot_id'), table_name='channel_sessions')
    op.drop_index(op.f('ix_channel_sessions_conversation_id'), table_name='channel_sessions')
    op.drop_index(op.f('ix_channel_sessions_identity_id'), table_name='channel_sessions')
    op.drop_index(op.f('ix_channel_sessions_platform_chat_id'), table_name='channel_sessions')
    op.create_index(op.f('channel_sessions_bot_id_idx'), 'channel_sessions', ['bot_id'], unique=False)
    op.create_index(op.f('channel_sessions_conversation_id_idx'), 'channel_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('channel_sessions_identity_id_idx'), 'channel_sessions', ['identity_id'], unique=False)
    op.create_index(op.f('channel_sessions_platform_chat_id_idx'), 'channel_sessions', ['platform_chat_id'], unique=False)
    op.drop_index(op.f('ix_chat_files_user_id'), table_name='chat_files')
    op.create_index(op.f('chat_files_user_id_idx'), 'chat_files', ['user_id'], unique=False)
    op.drop_index(op.f('ix_conversation_shares_conversation_id'), table_name='conversation_shares')
    op.drop_index(op.f('ix_conversation_shares_shared_with'), table_name='conversation_shares')
    op.create_index(op.f('conversation_shares_conversation_id_idx'), 'conversation_shares', ['conversation_id'], unique=False)
    op.create_index(op.f('conversation_shares_shared_with_idx'), 'conversation_shares', ['shared_with'], unique=False)
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('conversations_user_id_idx'), 'conversations', ['user_id'], unique=False)
    op.drop_index(op.f('ix_message_ratings_message_id'), table_name='message_ratings')
    op.drop_index(op.f('ix_message_ratings_user_id'), table_name='message_ratings')
    op.create_index(op.f('message_ratings_message_id_idx'), 'message_ratings', ['message_id'], unique=False)
    op.create_index(op.f('message_ratings_user_id_idx'), 'message_ratings', ['user_id'], unique=False)
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.create_index(op.f('messages_conversation_id_idx'), 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('ix_rag_documents_collection_name'), table_name='rag_documents')
    op.create_index(op.f('rag_documents_collection_name_idx'), 'rag_documents', ['collection_name'], unique=False)
    op.drop_index(op.f('ix_sync_logs_collection_name'), table_name='sync_logs')
    op.create_index(op.f('sync_logs_collection_name_idx'), 'sync_logs', ['collection_name'], unique=False)
    op.drop_index(op.f('ix_sync_sources_collection_name'), table_name='sync_sources')
    op.create_index(op.f('sync_sources_collection_name_idx'), 'sync_sources', ['collection_name'], unique=False)
    op.drop_index(op.f('ix_tool_calls_message_id'), table_name='tool_calls')
    op.create_index(op.f('tool_calls_message_id_idx'), 'tool_calls', ['message_id'], unique=False)
    op.drop_index(op.f('ix_user_slash_commands_user_id'), table_name='user_slash_commands')
    op.create_index(op.f('user_slash_commands_user_id_idx'), 'user_slash_commands', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_slash_commands_user_id_idx'), table_name='user_slash_commands')
    op.create_index(op.f('ix_user_slash_commands_user_id'), 'user_slash_commands', ['user_id'], unique=False)
    op.drop_index(op.f('tool_calls_message_id_idx'), table_name='tool_calls')
    op.create_index(op.f('ix_tool_calls_message_id'), 'tool_calls', ['message_id'], unique=False)
    op.drop_index(op.f('sync_sources_collection_name_idx'), table_name='sync_sources')
    op.create_index(op.f('ix_sync_sources_collection_name'), 'sync_sources', ['collection_name'], unique=False)
    op.drop_index(op.f('sync_logs_collection_name_idx'), table_name='sync_logs')
    op.create_index(op.f('ix_sync_logs_collection_name'), 'sync_logs', ['collection_name'], unique=False)
    op.drop_index(op.f('rag_documents_collection_name_idx'), table_name='rag_documents')
    op.create_index(op.f('ix_rag_documents_collection_name'), 'rag_documents', ['collection_name'], unique=False)
    op.drop_index(op.f('messages_conversation_id_idx'), table_name='messages')
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_index(op.f('message_ratings_user_id_idx'), table_name='message_ratings')
    op.drop_index(op.f('message_ratings_message_id_idx'), table_name='message_ratings')
    op.create_index(op.f('ix_message_ratings_user_id'), 'message_ratings', ['user_id'], unique=False)
    op.create_index(op.f('ix_message_ratings_message_id'), 'message_ratings', ['message_id'], unique=False)
    op.drop_index(op.f('conversations_user_id_idx'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.drop_index(op.f('conversation_shares_shared_with_idx'), table_name='conversation_shares')
    op.drop_index(op.f('conversation_shares_conversation_id_idx'), table_name='conversation_shares')
    op.create_index(op.f('ix_conversation_shares_shared_with'), 'conversation_shares', ['shared_with'], unique=False)
    op.create_index(op.f('ix_conversation_shares_conversation_id'), 'conversation_shares', ['conversation_id'], unique=False)
    op.drop_index(op.f('chat_files_user_id_idx'), table_name='chat_files')
    op.create_index(op.f('ix_chat_files_user_id'), 'chat_files', ['user_id'], unique=False)
    op.drop_index(op.f('channel_sessions_platform_chat_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_identity_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_conversation_id_idx'), table_name='channel_sessions')
    op.drop_index(op.f('channel_sessions_bot_id_idx'), table_name='channel_sessions')
    op.create_index(op.f('ix_channel_sessions_platform_chat_id'), 'channel_sessions', ['platform_chat_id'], unique=False)
    op.create_index(op.f('ix_channel_sessions_identity_id'), 'channel_sessions', ['identity_id'], unique=False)
    op.create_index(op.f('ix_channel_sessions_conversation_id'), 'channel_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_channel_sessions_bot_id'), 'channel_sessions', ['bot_id'], unique=False)
    op.drop_index(op.f('channel_identities_user_id_idx'), table_name='channel_identities')
    op.drop_index(op.f('channel_identities_platform_user_id_idx'), table_name='channel_identities')
    op.drop_index(op.f('channel_identities_platform_idx'), table_name='channel_identities')
    op.create_index(op.f('ix_channel_identities_user_id'), 'channel_identities', ['user_id'], unique=False)
    op.create_index(op.f('ix_channel_identities_platform_user_id'), 'channel_identities', ['platform_user_id'], unique=False)
    op.create_index(op.f('ix_channel_identities_platform'), 'channel_identities', ['platform'], unique=False)
    op.drop_index(op.f('channel_bots_platform_idx'), table_name='channel_bots')
    op.create_index(op.f('ix_channel_bots_platform'), 'channel_bots', ['platform'], unique=False)
    op.drop_index(op.f('webhook_deliveries_webhook_id_idx'), table_name='webhook_deliveries')
    op.drop_index(op.f('webhook_deliveries_created_at_idx'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('webhooks_user_id_idx'), table_name='webhooks')
    op.drop_table('webhooks')
    # ### end Alembic commands ###
